name: Simulator CI

on:
  push:
    branches:
      - main
  
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.12.0
        uses: actions/setup-python@v3
        with:
          python-version: 3.12.0
      - name: libs
        run: |
          sudo apt-get update 
          sudo apt-get install -y libxkbcommon-x11-0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-xinerama0 libxcb-xfixes0 libegl1-mesa libxcb-shape0 libxcb-cursor0
      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: CodeQuality Flake8
        run: |
          flake8 simulator.py

      - name: Run Tests
        run: |
          # pytest -rA   # Not PyQt errors.
